apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "airflow.fullname" . }}-workers-env"
data:
  airflow.cfg: |
    [core]
    fernet_key: {{ .Values.airflow.fernetKey }}
    sql_alchemy_conn: {{ .Values.airflow.sqlalchemy_connection }}
