kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.logs.shareName }}
  labels:
    app: {{ template "airflow.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeName: {{ .Values.persistence.logs.shareName }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.dags.shareName }}
  labels:
    app: {{ template "airflow.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeName: {{ .Values.persistence.dags.shareName }}
